[package]
name = "nautilus_model"
version = "0.1.0"
authors = ["Nautech Systems <info@nautechsystems.io>"]
edition = "2021"

[lib]
name = "nautilus_model"
crate-type = ["rlib", "staticlib"]

[dependencies]
nautilus_core = { path = "../core" }
pyo3 = "^0.16.5"

[dev-dependencies]
criterion = "0.3.5"
iai = "0.1"
rstest = "^0.15.0"

[build-dependencies]
cbindgen = "^0.20.0"

[[bench]]
name = "criterion_fixed_precision_benchmark"
harness = false
