[package]
name = "nautilus_model"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_model"
crate-type = ["rlib", "staticlib"]

[dependencies]
nautilus_core = { path = "../core" }
pyo3.workspace = true
rust-fsm.workspace = true
strum.workspace = true
thiserror.workspace = true

[features]
extension-module = [
    "pyo3/extension-module",
    "nautilus_core/extension-module",
]
default = []

[dev-dependencies]
criterion.workspace = true
iai.workspace = true
rstest.workspace = true

[build-dependencies]
cbindgen.workspace = true

[[bench]]
name = "criterion_fixed_precision_benchmark"
harness = false
