[package]
name = "nautilus_model"
version = "0.1.0"
authors = ["Nautech Systems <info@nautechsystems.io>"]
edition = "2021"

[lib]
name = "nautilus_model"
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
nautilus_core = { path = "../core" }
pyo3 = { version = "0.17.2" }

[features]
extension-module = [
    "pyo3/extension-module",
    "nautilus_core/extension-module",
]
default = []

[dev-dependencies]
criterion = "0.3.5"
iai = "0.1"
rstest = "0.15.0"

[build-dependencies]
cbindgen = "0.24.3"

[[bench]]
name = "criterion_fixed_precision_benchmark"
harness = false

