[package]
name = "nautilus-model"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_model"
crate-type = ["rlib", "staticlib"]

[dependencies]
nautilus-core = { path = "../core" }
anyhow.workspace = true
pyo3.workspace = true
rmp-serde.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true
derive_builder = "0.12.0"
evalexpr = "11.0.0"
lazy_static = "1.4.0"
tabled = "0.12.2"

[features]
extension-module = [
    "pyo3/extension-module",
    "nautilus-core/extension-module",
]
default = []

[dev-dependencies]
criterion.workspace = true
iai.workspace = true
rstest.workspace = true

[build-dependencies]
cbindgen.workspace = true

[[bench]]
name = "criterion_fixed_precision_benchmark"
harness = false
