[package]
name = "nautilus-model"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_model"
crate-type = ["rlib", "staticlib"]

[dependencies]
nautilus-core = { path = "../core" }
anyhow = { workspace = true }
indexmap = { workspace = true }
once_cell = { workspace = true }
pyo3 = { workspace = true, optional = true }
rstest = { workspace = true, optional = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
thousands = { workspace = true }
ustr = { workspace = true }
chrono = { workspace = true }
derive_builder = "0.20.0"
evalexpr = "11.3.0"
tabled = "0.15.0"

[dev-dependencies]
criterion = { workspace = true }
float-cmp = { workspace = true }
iai = { workspace = true }

[build-dependencies]
cbindgen = { workspace = true, optional = true }

[features]
default = ["trivial_copy"]
trivial_copy = []  # Enables deriving the `Copy` trait for data types (should be included in default)
extension-module = [
  "pyo3/extension-module",
  "nautilus-core/extension-module",
]
ffi = ["cbindgen", "nautilus-core/ffi"]
python = ["pyo3", "nautilus-core/python"]
stubs = ["rstest"]

[[bench]]
name = "criterion_fixed_precision_benchmark"
harness = false
