[package]
name = "nautilus-databento"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_databento"
crate-type = ["rlib", "staticlib", "cdylib"]

[[bin]]
name = "databento-sandbox"
path = "bin/sandbox.rs"

[dependencies]
nautilus-core = { path = "../../core" }
nautilus-model = { path = "../../model" }
anyhow = { workspace = true }
indexmap = { workspace = true }
itoa = { workspace = true }
log = { workspace = true }
pyo3 = { workspace = true, optional = true }
pyo3-async-runtimes = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
ustr = { workspace = true }
databento = { version = "0.17.0" }
fallible-streaming-iterator = { version = "0.1.9" }
time = { version = "0.3.37" }

[dev-dependencies]
nautilus-test-kit = { path = "../../test_kit" }
criterion = { workspace = true }
rstest = { workspace = true }
tracing-test = { workspace = true }

[features]
default = ["python", "nautilus-core/ffi"]
extension-module = [
  "pyo3/extension-module",
  "nautilus-core/extension-module",
  "nautilus-model/extension-module",
]
python = [
  "pyo3",
  "pyo3-async-runtimes",
  "nautilus-core/python",
  "nautilus-model/python",
]
