[package]
name = "nautilus-adapters"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_adapters"
crate-type = ["rlib", "staticlib", "cdylib"]

[[bin]]
name = "databento-sandbox"
path = "src/databento/bin/sandbox.rs"

[[bin]]
name = "tardis-machine"
path = "src/tardis/bin/example.rs"

[dependencies]
nautilus-common = { path = "../common" }
nautilus-core = { path = "../core" }
nautilus-model = { path = "../model", features = ["stubs"] }
anyhow = { workspace = true }
async-stream = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
itoa = { workspace = true }
pyo3 = { workspace = true, optional = true }
pyo3-asyncio-0-21 = { workspace = true, optional = true }
rand = { workspace = true }
ring = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true, optional = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
ustr = { workspace = true }
csv = "1.3.0"
databento = { version = "0.14.1", optional = true }
fallible-streaming-iterator = "0.1.9"
flate2 = "1.0.34"
pem = "3.0.4"
time = "0.3.36"
urlencoding = { version = "2.1.3", optional = true }

[dev-dependencies]
nautilus-test-kit = { path = "../test_kit" }
criterion = { workspace = true }
rstest = { workspace = true }
tracing-test = { workspace = true }

[features]
default = ["databento", "ffi", "python", "tardis"]
extension-module = [
  "pyo3/extension-module",
  "nautilus-common/extension-module",
  "nautilus-core/extension-module",
  "nautilus-model/extension-module",
]
databento = ["dep:databento", "python"]
ffi = [
  "nautilus-common/ffi",
  "nautilus-core/ffi",
  "nautilus-model/ffi",
]
python = [
  "pyo3",
  "pyo3-asyncio-0-21",
  "nautilus-common/python",
  "nautilus-core/python",
  "nautilus-model/python",
]
tardis = ["python", "tokio-tungstenite", "urlencoding"]
