[package]
name = "nautilus-adapters"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_adapters"
crate-type = ["rlib", "staticlib", "cdylib"]

[[bin]]
name = "sandbox"
path = "src/databento/bin/sandbox.rs"

[dependencies]
nautilus-common = { path = "../common" }
nautilus-core = { path = "../core" }
nautilus-model = { path = "../model", features = ["stubs"] }
anyhow = { workspace = true }
chrono = { workspace = true }
indexmap = { workspace = true }
itoa = { workspace = true }
log = { workspace = true }
pyo3 = { workspace = true, optional = true }
pyo3-asyncio = { workspace = true, optional = true }
rand = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
ustr = { workspace = true }
databento = { version = "0.7.1", optional = true }
streaming-iterator = "0.1.9"
time = "0.3.34"

[dev-dependencies]
criterion = { workspace = true }
rstest = { workspace = true }

[features]
default = ["ffi", "python"]
extension-module = [
  "pyo3/extension-module",
  "nautilus-common/extension-module",
  "nautilus-core/extension-module",
  "nautilus-model/extension-module",
]
databento = ["dep:databento", "python"]
ffi = [
  "nautilus-common/ffi",
  "nautilus-core/ffi",
  "nautilus-model/ffi",
]
python = [
  "pyo3",
  "pyo3-asyncio",
  "nautilus-common/python",
  "nautilus-core/python",
  "nautilus-model/python",
]
