[package]
name = "nautilus-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[[bin]]
name = "nautilus"
path = "src/bin/cli.rs"

[dependencies]
nautilus-common = { path = "../common"}
nautilus-model = { path = "../model" }
nautilus-core = { path = "../core" }
nautilus-infrastructure = { path = "../infrastructure" , features = ["postgres"] }
anyhow = { workspace = true }
log = { workspace = true }
tokio = {workspace = true}
clap = { version = "4.5.13", features = ["derive", "env"] }
clap_derive = { version = "4.5.13" }
dotenvy = { version = "0.15.7" }
simple_logger = "5.0.0"
