[package]
name = "nautilus_catalog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "nautilus_catalog"
crate-type = ["rlib", "staticlib"]

[dependencies]
nautilus_core = { path = "../core" }
nautilus_model = { path = "../model" }
pyo3 = { version = "0.16.5" }
arrow2 = { version = "0.12.0", features = [ "io_parquet", "io_csv_read", "compute_comparison" ] }

[build-dependencies]
cbindgen = "^0.20.0"
