cognitive-complexity-threshold = 10
allow-expect-in-tests = true
allow-unwrap-in-tests = true
doc-valid-idents = [
  "BaseSwap",
  "BaseX",
  "BitMEX",
  "DataFusion",
  "DeFi",
  "HyperSync",
  "MessagePack",
  "NautilusTrader",
  "PancakeSwap",
  "PascalCase",
  "PnL",
  "PnLs",
  "PostgreSQL",
  "PyO3",
  "SushiSwap",
  "SQLx",
  "..",
]
