[package]
name = "nautilus-tardis"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_tardis"
crate-type = ["rlib", "staticlib", "cdylib"]

[[bin]]
name = "tardis-csv"
path = "bin/example_csv.rs"

[[bin]]
name = "tardis-http"
path = "bin/example_http.rs"

[[bin]]
name = "tardis-replay"
path = "bin/example_replay.rs"

[dependencies]
nautilus-core = { path = "../../core" }
nautilus-model = { path = "../../model" }
nautilus-serialization = { path = "../../serialization" }
anyhow = { workspace = true }
arrow = { workspace = true }
async-stream = { workspace = true }
chrono = { workspace = true }
derive_builder = { workspace = true }
futures-util = { workspace = true }
heck = { workspace = true }
pyo3 = { workspace = true, optional = true }
pyo3-async-runtimes = { workspace = true, optional = true }
reqwest = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
thousands = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ustr = { workspace = true }
uuid = { workspace = true }
csv = "1.3.1"
flate2 = "1.0.35"
urlencoding = "2.1.3"

[dev-dependencies]
nautilus-test-kit = { path = "../../test_kit" }
criterion = { workspace = true }
rstest = { workspace = true }
tracing-test = { workspace = true }

[features]
default = ["python", "nautilus-core/ffi"]
extension-module = [
  "pyo3/extension-module",
  "nautilus-core/extension-module",
  "nautilus-model/extension-module",
]
python = [
  "pyo3",
  "pyo3-async-runtimes",
  "nautilus-core/python",
  "nautilus-model/python",
]
