[package]
name = "nautilus-risk"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_risk"
crate-type = ["rlib", "cdylib"]

[dependencies]
nautilus-common = { path = "../common" }
nautilus-core = { path = "../core" }
nautilus-execution = { path = "../execution" }
nautilus-model = { path = "../model", features = ["stubs"] }
nautilus-portfolio = { path = "../portfolio" }
log = { workspace = true }
pyo3 = { workspace = true, optional = true }
rust_decimal = { workspace = true }
thiserror = { workspace = true }
ustr = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
rstest = { workspace = true }

[features]
default = ["python"]
extension-module = [
  "pyo3/extension-module",
  "nautilus-common/extension-module",
  "nautilus-core/extension-module",
  "nautilus-execution/extension-module",
  "nautilus-model/extension-module",
]
python = [
  "pyo3",
  "nautilus-common/python",
  "nautilus-core/python",
  "nautilus-execution/python",
  "nautilus-model/python",
]
