[package]
name = "nautilus-indicators"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_indicators"
crate-type = ["rlib", "cdylib"]

[dependencies]
nautilus-core = { path = "../core" }
nautilus-model = { path = "../model" }
anyhow = { workspace = true }
pyo3 = { workspace = true, optional = true }
strum = { workspace = true }

[dev-dependencies]
rstest.workspace = true

[features]
extension-module = [
    "pyo3/extension-module",
    "nautilus-core/extension-module",
    "nautilus-model/extension-module",
]
python = ["pyo3"]
default = ["python"]
