[package]
name = "nautilus_core"
version = "0.1.0"
authors = ["Nautech Systems <info@nautechsystems.io>"]
edition = "2021"

[lib]
name = "nautilus_core"
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
chrono = "^0.4.19"
uuid = { version = "^0.8.2", features = ["v4"] }
lazy_static = "^1.4.0"

[dependencies.pyo3]
git = "https://github.com/pyo3/pyo3"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[dev-dependencies]
criterion = "^0.3.5"
iai = "^0.1"
rstest = "^0.15.0"

[build-dependencies]
cbindgen = "^0.20.0"

[[bench]]
name = "criterion_time_benchmark"
harness = false
