[package]
name = "nautilus_core"
version = "0.1.0"
authors = ["Nautech Systems <info@nautechsystems.io>"]
edition = "2021"

[lib]
name = "nautilus_core"
crate-type = ["rlib", "staticlib"]

[dependencies]
cbindgen = "^0.20.0"
pyo3 = "^0.16.5"
uuid = { version = "^0.8.2", features = ["v4"] }

[build-dependencies]
cbindgen = "^0.20.0"
