[package]
name = "nautilus-persistence"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_persistence"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
nautilus-core = { path = "../core" }
nautilus-model = { path = "../model" }
chrono.workspace = true
futures.workspace = true
pyo3.workspace = true
pyo3-asyncio.workspace = true
rand.workspace = true
tokio.workspace = true
thiserror.workspace = true
binary-heap-plus = "0.5.0"
compare = "0.1.0"
# FIX: default feature "crypto_expressions" using using blake3 fails build on windows: https://github.com/BLAKE3-team/BLAKE3/issues/298
datafusion = { version = "27.0.0", default-features = false, features = ["compression", "regex_expressions", "unicode_expressions"] }
pin-project-lite = "0.2.9"

[features]
extension-module = [
  "pyo3/extension-module", 
  "nautilus-core/extension-module", 
  "nautilus-model/extension-module",
]
default = []

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "bench_persistence"
harness = false
