[package]
name = "nautilus-pyo3"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_pyo3"
crate-type = ["cdylib"]

[dependencies]
nautilus-adapters = { path = "../adapters", features = ["python", "databento"] }
nautilus-common = { path = "../common" , features = ["python"] }
nautilus-core = { path = "../core" , features = ["python"] }
nautilus-cryptography = { path = "../cryptography" , features = ["python"] }
nautilus-indicators = { path = "../indicators" , features = ["python"] }
nautilus-infrastructure = { path = "../infrastructure", features = ["python"] }
nautilus-model = { path = "../model" , features = ["python"] }
nautilus-network = { path = "../network" , features = ["python"] }
nautilus-persistence = { path = "../persistence" , features = ["python"] }
nautilus-serialization = { path = "../serialization" , features = ["python"] }
nautilus-test-kit = { path = "../test_kit" , features = ["python"] }
pyo3 = { workspace = true }

[features]
default = []
extension-module = [
    "pyo3/extension-module",
    "nautilus-adapters/extension-module",
    "nautilus-common/extension-module",
    "nautilus-core/extension-module",
    "nautilus-cryptography/extension-module",
    "nautilus-indicators/extension-module",
    "nautilus-infrastructure/extension-module",
    "nautilus-model/extension-module",
    "nautilus-persistence/extension-module",
    "nautilus-serialization/extension-module",
    "nautilus-test-kit/extension-module",
]
ffi = [
    "nautilus-adapters/ffi",
    "nautilus-common/ffi",
    "nautilus-core/ffi",
    "nautilus-model/ffi",
    "nautilus-persistence/ffi",
]
