[package]
name = "nautilus-pyo3"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_pyo3"
crate-type = ["cdylib"]

[dependencies]
nautilus-common = { path = "../common" }
nautilus-indicators = { path = "../indicators" }
nautilus-model = { path = "../model" }
nautilus-persistence = { path = "../persistence" }
nautilus-network = { path = "../network" }
pyo3.workspace = true

[features]
extension-module = [
    "pyo3/extension-module",
    "nautilus-indicators/extension-module",
    "nautilus-model/extension-module",
    "nautilus-persistence/extension-module",
]
default = []
