[package]
name = "nautilus_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "nautilus_common"
crate-type = ["rlib", "staticlib"]

[dependencies]
nautilus_core = { path = "../core" }
nautilus_model = { path = "../model" }
pyo3 = { version = "0.16.5" }
arrow2 = { version = "0.12.0", features = [ "io_parquet", "io_csv_read" ] }
chrono = "^0.4.19"
pyo3 = { version = "^0.16.5" }

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[build-dependencies]
cbindgen = "^0.20.0"
