[package]
name = "nautilus-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_common"
crate-type = ["rlib", "staticlib"]

[dependencies]
nautilus-core = { path = "../core" }
nautilus-model = { path = "../model", features = ["stubs"]}
anyhow = { workspace = true }
chrono = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
pyo3 = { workspace = true, optional = true }
redis = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
ustr = { workspace = true }
tracing = { workspace = true }
sysinfo = "0.30.5"
# Disable default feature "tracing-log" since it interferes with custom logging
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["smallvec", "fmt", "ansi", "std", "env-filter"] }

[dev-dependencies]
tempfile = { workspace = true }
rstest = { workspace = true }

[features]
extension-module = [
    "pyo3/extension-module",
    "nautilus-core/extension-module",
    "nautilus-model/extension-module",
]
ffi = ["cbindgen"]
python = ["pyo3"]
redis = ["dep:redis"]
default = ["ffi", "python", "redis"]

[build-dependencies]
cbindgen = { workspace = true, optional = true }
