[package]
name = "nautilus-backtest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description.workspace = true
categories.workspace = true
keywords.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
name = "nautilus_backtest"
crate-type = ["rlib", "staticlib"]

[features]
default = []
extension-module = [
  "pyo3/extension-module",
  "nautilus-common/extension-module",
  "nautilus-core/extension-module",
  "nautilus-execution/extension-module",
  "nautilus-model/extension-module",
]
ffi = [
  "cbindgen",
  "nautilus-core/ffi",
  "nautilus-common/ffi",
  "nautilus-execution/ffi",
  "nautilus-model/ffi",
]
python = [
  "pyo3",
  "nautilus-core/python",
  "nautilus-common/python",
  "nautilus-execution/python",
  "nautilus-model/python",
]
"clock_v2" = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
nautilus-common = { path = "../common" }
nautilus-core = { path = "../core" }
nautilus-data = { path = "../data" }
nautilus-execution = { path = "../execution" }
nautilus-model = { path = "../model" , features = ["stubs"]}
nautilus-system = { path = "../system" }
anyhow = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
pyo3 = { workspace = true, optional = true }
ustr = { workspace = true }
rust_decimal = { workspace = true }
rand = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
rstest = { workspace = true}

[build-dependencies]
cbindgen = { workspace = true, optional = true }
