[package]
name = "nautilus-model"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_model"
crate-type = ["rlib", "staticlib"]

[dependencies]
nautilus-core = { path = "../core" }
anyhow = { workspace = true }
chrono = { workspace = true }
derive_builder = { workspace = true }
indexmap = { workspace = true }
once_cell = { workspace = true }
pyo3 = { workspace = true, optional = true }
rstest = { workspace = true, optional = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
thousands = { workspace = true }
ustr = { workspace = true }
evalexpr = "12.0.2"
implied-vol = { version = "1.0.1", features = ["normal-distribution"] }
tabled = "0.18.0"

[dev-dependencies]
nautilus-databento = { path = "../adapters/databento" }
nautilus-test-kit = { path = "../test_kit" }
criterion = { workspace = true }
float-cmp = { workspace = true }
iai = { workspace = true }

[build-dependencies]
cbindgen = { workspace = true, optional = true }

[features]
default = []
extension-module = [
  "pyo3/extension-module",
  "nautilus-core/extension-module",
]
ffi = ["cbindgen", "nautilus-core/ffi"]
python = ["pyo3", "nautilus-core/python"]
stubs = ["rstest"]
high-precision = []

[[bench]]
name = "bench_book_iai"
harness = false

[[bench]]
name = "bench_fixed_precision_criterion"
harness = false

[[bench]]
name = "bench_fixed_precision_iai"
harness = false
