[package]
name = "nautilus-infrastructure"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_infrastructure"
crate-type = ["rlib", "cdylib"]

[dependencies]
nautilus-common = { path = "../common", features = ["python"] }
nautilus-core = { path = "../core" , features = ["python"] }
nautilus-model = { path = "../model" , features = ["python", "stubs"] }
anyhow = { workspace = true }
pyo3 = { workspace = true, optional = true }
log = { workspace = true }
rmp-serde = { workspace = true }
rust_decimal = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = {workspace = true }
ustr = { workspace = true }
redis = { version = "0.25.4", features = [
    "connection-manager",
    "keep-alive",
    "tls-rustls",
    "tls-rustls-webpki-roots",
    "tokio-comp",
    "tokio-rustls-comp",
], optional = true }
sqlx = { version = "0.7.4", features = [
    "sqlite",
    "postgres",
    "any",
    "runtime-tokio",
    "json"
], optional = true }

[dev-dependencies]
rstest = { workspace = true }
serial_test = { version = "3.1.1" }

[features]
default = ["redis"]  # redis needed by `nautilus_trader` by default for now
extension-module = [
    "pyo3/extension-module",
    "nautilus-common/extension-module",
    "nautilus-core/extension-module",
    "nautilus-model/extension-module",
]
python = ["pyo3"]
redis = ["dep:redis"]
postgres = ["dep:sqlx"]
