[package]
name = "nautilus-infrastructure"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_infrastructure"
crate-type = ["rlib", "cdylib"]

[dependencies]
nautilus-common = { path = "../common", features = ["redis"] }
nautilus-core = { path = "../core" , features = ["python"] }
nautilus-model = { path = "../model" , features = ["python"] }
anyhow = { workspace = true }
pyo3 = { workspace = true, optional = true }
redis = { workspace = true, optional = true }
rmp-serde = { workspace = true }
serde_json = { workspace = true }
tracing = {workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[features]
default = ["redis"]
extension-module = [
    "pyo3/extension-module",
    "nautilus-common/extension-module",
    "nautilus-core/extension-module",
    "nautilus-model/extension-module",
]
python = ["pyo3"]
redis = ["dep:redis"]
