[package]
name = "nautilus-infrastructure"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_infrastructure"
crate-type = ["rlib", "cdylib"]

[dependencies]
nautilus-common = { path = "../common" }
nautilus-core = { path = "../core" }
nautilus-model = { path = "../model" }
anyhow = { workspace = true }
pyo3 = { workspace = true, optional = true }
redis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }

[dev-dependencies]
rstest.workspace = true

[features]
extension-module = [
    "pyo3/extension-module",
    "nautilus-common/extension-module",
    "nautilus-core/extension-module",
    "nautilus-model/extension-module",
]
python = ["pyo3"]
default = ["python"]
