[workspace]
resolver = "2"
members = [
    "backtest",
    "common",
    "core",
    "indicators",
    "model",
    "network",
    "network/tokio-tungstenite",
    "persistence",
    "pyo3",
]

[workspace.package]
rust-version = "1.74.0"
version = "0.12.0"
edition = "2021"
authors = ["Nautech Systems <info@nautechsystems.io>"]
description = "A high-performance algorithmic trading platform and event-driven backtester"
documentation = "https://docs.nautilustrader.io"

[workspace.dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
futures = "0.3.29"
indexmap = "2.1.0"
once_cell = "1.18.0"
pyo3 = { version = "0.19.2", features = ["rust_decimal"] }
pyo3-asyncio = { version = "0.19.0", features = ["tokio-runtime", "tokio", "attributes"] }
rand = "0.8.5"
rmp-serde = "1.1.2"
rust_decimal = "1.33.1"
rust_decimal_macros = "1.33.1"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.50"
tracing = "0.1.40"
tokio = { version = "1.34.0", features = ["full"] }
ustr = { git = "https://github.com/anderslanglands/ustr", features = ["serde"] }
uuid = { version = "1.5.0", features = ["v4"] }

# dev-dependencies
criterion = "0.5.1"
float-cmp = "0.9.0"
iai = "0.1"
rstest = "0.18.2"
tempfile = "3.8.1"

# build-dependencies
cbindgen = "0.26.0"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = false  # Fails Cython build if true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256

[profile.test]
opt-level = 0
debug = true
debug-assertions = true  # Fails Cython build if true (OK for cargo test)
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
strip = true
panic = "abort"
incremental = false
codegen-units = 1

[profile.release-debugging]
inherits = "release"
incremental = true
debug = true
strip = false
