[workspace]
members = [
    "common",
    "core",
    "model",
    "persistence",
    "pyo3"
]

[workspace.package]
rust-version = "1.66.1"
version = "0.2.0"
edition = "2021"
authors = ["Nautech Systems <info@nautechsystems.io>"]
description = "A high-performance algorithmic trading platform and event-driven backtester"
documentation = "https://docs.nautilustrader.io"

[workspace.dependencies]
chrono = "0.4.22"
pyo3 = "0.18.0"
rand = "0.8.5"
rust-fsm = "0.6.1"
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.38"
uuid = { version = "1.2.2", features = ["v4"] }

# dev-dependencies
criterion = "0.4.0"
iai = "0.1"
rstest = "0.16.0"

# build-dependencies
cbindgen = "0.24.3"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = false  # Fails Cython build if true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256

[profile.test]
opt-level = 0
debug = true
debug-assertions = true  # Fails Cython build if true (OK for cargo test)
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
