[workspace]
members = [
    "backtest",
    "common",
    "core",
    "indicators",
    "model",
    "network",
    "network/tokio-tungstenite",
    "persistence",
    "pyo3"
]

[workspace.package]
rust-version = "1.70.0"
version = "0.7.0"
edition = "2021"
authors = ["Nautech Systems <info@nautechsystems.io>"]
description = "A high-performance algorithmic trading platform and event-driven backtester"
documentation = "https://docs.nautilustrader.io"

[workspace.dependencies]
anyhow = "1.0.71"
chrono = "0.4.26"
futures = "0.3.28"
pyo3 = "0.19.1"
pyo3-asyncio = { git = "https://github.com/nautechsystems/pyo3-asyncio.git", features = ["tokio-runtime", "tokio", "attributes"] }
pyo3-macros = "0.19.1"
rand = "0.8.5"
rmp-serde = "1.1.1"
rust_decimal = "1.30.0"
rust_decimal_macros = "1.29.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.102"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.43"
tracing = "0.1.37"
tokio = { version = "1.29.1", features = ["full"] }
uuid = { version = "1.4.0", features = ["v4"] }

# dev-dependencies
criterion = "0.4.0"
iai = "0.1"
rstest = "0.17.0"
tempfile = "3.6.0"

# build-dependencies
cbindgen = "0.24.5"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = false  # Fails Cython build if true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256

[profile.test]
opt-level = 0
debug = true
debug-assertions = true  # Fails Cython build if true (OK for cargo test)
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
strip = true
panic = "abort"
incremental = false
codegen-units = 1
