[workspace]
resolver = "2"
members = [
    "accounting",
    "adapters",
    "backtest",
    "common",
    "core",
    "execution",
    "indicators",
    "infrastructure",
    "model",
    "network",
    "network/tokio-tungstenite",
    "persistence",
    "pyo3",
]

[workspace.package]
rust-version = "1.77.0"
version = "0.20.0"
edition = "2021"
authors = ["Nautech Systems <info@nautechsystems.io>"]
description = "A high-performance algorithmic trading platform and event-driven backtester"
documentation = "https://docs.nautilustrader.io"

[workspace.dependencies]
anyhow = "1.0.81"
chrono = "0.4.35"
futures = "0.3.30"
indexmap = { version = "2.2.5", features = ["serde"] }
itoa = "1.0.10"
once_cell = "1.19.0"
log = { version = "0.4.21", features = ["std", "kv_unstable", "serde", "release_max_level_debug"] }
pyo3 = { version = "0.20.3", features = ["rust_decimal"] }
pyo3-asyncio = { version = "0.20.0", features = ["tokio-runtime", "tokio", "attributes"] }
rand = "0.8.5"
redis = { version = "0.25.2", features = [
    "connection-manager",
    "keep-alive",
    "tls-rustls",
    "tls-rustls-webpki-roots",
    "tokio-comp",
    "tokio-rustls-comp",
] }
rmp-serde = "1.1.2"
rust_decimal = "1.34.3"
rust_decimal_macros = "1.34.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
strum = { version = "0.26.2", features = ["derive"] }
thiserror = "1.0.58"
thousands = "0.2.0"
tracing = "0.1.40"
tokio = { version = "1.36.0", features = ["full"] }
ustr = { version = "1.0.0", features = ["serde"] }
uuid = { version = "1.8.0", features = ["v4"] }

# dev-dependencies
criterion = "0.5.1"
float-cmp = "0.9.0"
iai = "0.1"
rstest = "0.18.2"
tempfile = "3.10.1"

# build-dependencies
cbindgen = "0.26.0"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = false  # Fails Cython build if true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256

[profile.test]
opt-level = 0
debug = true
debug-assertions = true  # Fails Cython build if true (OK for cargo test)
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
strip = true
panic = "abort"
incremental = false
codegen-units = 1

[profile.release-debugging]
inherits = "release"
incremental = true
debug = true
strip = false
