[package]
name = "nautilus-network"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_network"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
nautilus-core = { path = "../core" }
anyhow = { workspace = true }
futures = { workspace = true }
pyo3 = { workspace = true, optional = true }
pyo3-asyncio = { workspace = true, optional = true }
tracing = { workspace = true }
tokio = { workspace = true }
dashmap = "5.5.3"
futures-util = "0.3.30"
http = "1.1.0"
hyper = "1.2.0"
nonzero_ext = "0.3.0"
reqwest = "0.11.27"
tokio-tungstenite = { path = "./tokio-tungstenite", features = ["rustls-tls-native-roots"] }

[dev-dependencies]
criterion = { workspace = true }
serde_json = { workspace = true }
rstest = { workspace = true }
axum = "0.7.4"
tracing-test = "0.2.4"

[features]
default = ["python"]
extension-module = [
  "pyo3/extension-module",
  "nautilus-core/extension-module",
]
python = ["pyo3", "pyo3-asyncio"]
