[package]
name = "nautilus_network"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_network"
crate-type = ["rlib", "staticlib", "cdylib" ]

[dependencies]
nautilus_core = { path = "../core" }
pyo3.workspace = true
pyo3-asyncio.workspace = true
serde_json.workspace = true
tokio.workspace = true
hyper = { version = "0.14.26", features = ["client", "http1"] }
hyper-tls = "0.5.0"

[dev-dependencies]
httptest = "0.15.4" 

[features]
extension-module = ["pyo3/extension-module", "nautilus_core/extension-module"]
default = []
