[package]
name = "nautilus-network"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_network"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
nautilus-core = { path = "../core" }
anyhow = { workspace = true }
futures = { workspace = true }
pyo3 = { workspace = true, optional = true }
pyo3-asyncio = { workspace = true, optional = true }
tracing = { workspace = true }
tokio = { workspace = true }
futures-util = "0.3.28"
hyper = { version = "0.14.27", features = ["client", "http1", "server"] }
hyper-tls = "0.5.0"
tokio-tungstenite = { path = "./tokio-tungstenite", features = ["rustls-tls-native-roots"] }
dashmap = "5.5.1"
nonzero_ext = "0.3.0"

[dev-dependencies]
criterion = { workspace = true }
serde_json = { workspace = true }
tracing-test = "0.2.4"
rstest.workspace = true

[features]
extension-module = [
  "pyo3/extension-module",
  "nautilus-core/extension-module",
]
python = ["pyo3", "pyo3-asyncio"]
default = ["python"]
