[package]
name = "nautilus-live"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_live"
crate-type = ["rlib", "cdylib"]

[dependencies]
nautilus-common = { path = "../common" }
nautilus-core = { path = "../core" }
nautilus-data = { path = "../data" }
nautilus-execution = { path = "../execution" }
nautilus-model = { path = "../model", features = ["stubs"] }
nautilus-portfolio = { path = "../portfolio" }
nautilus-risk = { path = "../risk" }
anyhow = { workspace = true }
chrono = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
pyo3 = { workspace = true, optional = true }
rand = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
rstest = { workspace = true }

[features]
default = ["ffi", "python"]
extension-module = [
  "pyo3/extension-module",
  "nautilus-common/extension-module",
  "nautilus-core/extension-module",
  "nautilus-data/extension-module",
  "nautilus-execution/extension-module",
  "nautilus-model/extension-module",
  "nautilus-portfolio/extension-module",
  "nautilus-risk/extension-module",
]
ffi = [
  "nautilus-common/ffi",
  "nautilus-core/ffi",
  "nautilus-model/ffi",
]
python = [
  "pyo3",
  "nautilus-common/python",
  "nautilus-core/python",
  "nautilus-data/python",
  "nautilus-execution/python",
  "nautilus-model/python",
  "nautilus-portfolio/python",
  "nautilus-risk/python",
]
clock_v2 = ["nautilus-common/clock_v2"]
